[FREELOADER]
DefaultOS=Setup_LogFile_Halaacpi
TimeOut=10

[Display]
TitleText=ReactOS Setup
StatusBarColor=Cyan
StatusBarTextColor=Black
BackdropTextColor=White
BackdropColor=Blue
BackdropFillStyle=Medium
TitleBoxTextColor=White
TitleBoxColor=Red
MessageBoxTextColor=White
MessageBoxColor=Blue
MenuTextColor=Default
MenuColor=Black
TextColor=Default
SelectedTextColor=Black
SelectedColor=Default
ShowTime=No
MenuBox=No
CenterMenu=No
MinimalUI=Yes
TimeText=Seconds until highlighted choice will be started automatically:   

[Operating Systems]
Setup_Com_Halaacpi="Setup (Debug COM) ACPI APIC UP (halaacpi.dll)"
Setup_Com_Kd0_Halaacpi="Setup (Debug COM + KD0) ACPI APIC UP (halaacpi.dll)"
Setup_Net_Halaacpi="Setup (Debug NET) ACPI APIC UP (halaacpi.dll)"
Setup_LogFile_Halaacpi="Setup (Log file + KD0) (halaacpi.dll)"
Setup_Com_Halacpi="Setup (Debug COM) ACPI PIC (halacpi.dll)"
;Setup_Debug_Hal="Setup (Debug) Standard PC (hal.dll) !Installed OS not work now!"
;Setup="Setup (Get Options from txtsetup.sif)"

[Setup]
[Setup_Com_Halaacpi]
BootType=ReactOSSetup
Options=/NOGUIBOOT /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /FIRSTCHANCE /HAL=halaacpi.dll

[Setup_Com_Kd0_Halaacpi]
BootType=ReactOSSetup
Options=/NOGUIBOOT /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /DEBUGKD0=COMKD0-COM1-115200,SCREENKD0,FILEKD0 /FIRSTCHANCE /HAL=halaacpi.dll

[Setup_Net_Halaacpi]
BootType=ReactOSSetup
Options=/NOGUIBOOT /DEBUG /DEBUGPORT=NET /W2003 /HOST_IP=10.0.5.5 /HOST_PORT=50000 /ENCRYPTION_KEY=make.reactos.great.always /CPUFREQ=3000 /TARGET_IP=10.0.5.4 /SOS /FIRSTCHANCE /HAL=halaacpi.dll

[Setup_LogFile_Halaacpi]
BootType=ReactOSSetup
Options=/NOGUIBOOT /DEBUG /DEBUGPORT=FILE /DEBUGKD0=COMKD0-COM1-115200,SCREENKD0,FILEKD0 /FIRSTCHANCE /HAL=halaacpi.dll

[Setup_Com_Halacpi]
BootType=ReactOSSetup
Options=/NOGUIBOOT /KDSERIAL /DEBUGPORT=COM1 /FIRSTCHANCE /HAL=halacpi.dll

[Setup_Debug_Hal]
BootType=ReactOSSetup
Options=/NOGUIBOOT /KDSERIAL /DEBUGPORT=COM1 /FIRSTCHANCE /HAL=hal.dll

[Setup]
BootType=ReactOSSetup

