[FREELOADER]
DefaultOS=LiveCD_RamDisk_Halaacpi
TimeOut=10

[Display]
TitleText=ReactOS Hybrid-CD
StatusBarColor=Cyan
StatusBarTextColor=Black
BackdropTextColor=White
BackdropColor=Blue
BackdropFillStyle=Medium
TitleBoxTextColor=White
TitleBoxColor=Red
MessageBoxTextColor=White
MessageBoxColor=Blue
MenuTextColor=Default
MenuColor=Black
TextColor=Default
SelectedTextColor=Black
SelectedColor=Default
ShowTime=No
MenuBox=No
CenterMenu=No
MinimalUI=Yes
TimeText=Seconds until highlighted choice will be started automatically:   

[Operating Systems]
Setup_Com_Halaacpi="Setup (Debug COM) ACPI APIC UP (halaacpi.dll)"

LiveCD_Halaacpi="Live ACPI APIC UP (halaacpi.dll)"
LiveCD_Com_Halaacpi="Live (Debug COM) (halaacpi.dll)"
LiveCD_Screen_Halaacpi="Live (Debug Screen) (halaacpi.dll)"
LiveCD_LogFile_Halaacpi="Live (Debug Log file) (halaacpi.dll)"

LiveCD_RamDisk_Halaacpi="LiveCD ACPI APIC UP in RAM (halaacpi.dll)"
LiveCD_RamDisk_Com_Halaacpi="LiveCD (Debug COM) in RAM (halaacpi.dll)"
LiveCD_RamDisk_Screen_Halaacpi="LiveCD (Debug Screen) in RAM (halaacpi.dll)"
LiveCD_RamDisk_LogFile_Halaacpi="LiveCD (Debug Log file) in RAM (halaacpi.dll)"

[Setup_Com_Halaacpi]
BootType=ReactOSSetup
SystemPath=\bootcd
Options=/NOGUIBOOT /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /FIRSTCHANCE /HAL=halaacpi.dll

[LiveCD_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/MININT /MININT /HAL=halaacpi.dll

[LiveCD_Com_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /MININT /HAL=halaacpi.dll

[LiveCD_Screen_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /SOS /MININT /HAL=halaacpi.dll

[LiveCD_LogFile_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=FILE /SOS /MININT /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\ArcName\multi(0)disk(0)rdisk(0)partition(1)\debug.log /SOS /MININT /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /MININT /HAL=halaacpi.dll

[LiveCD_RamDisk_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_Com_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_Screen_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_LogFile_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=FILE /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\ArcName\multi(0)disk(0)rdisk(0)partition(1)\debug.log /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll
