[FREELOADER]
DefaultOS=Setup_LogFile+_Halaacpi
TimeOut=10

[Display]
TitleText=ReactOS Hybrid-CD
StatusBarColor=Cyan
StatusBarTextColor=Black
BackdropTextColor=White
BackdropColor=Blue
BackdropFillStyle=Medium
TitleBoxTextColor=White
TitleBoxColor=Red
MessageBoxTextColor=White
MessageBoxColor=Blue
MenuTextColor=Default
MenuColor=Black
TextColor=Default
SelectedTextColor=Black
SelectedColor=Default
ShowTime=No
MenuBox=No
CenterMenu=No
MinimalUI=Yes
TimeText=Seconds until highlighted choice will be started automatically:   

[Operating Systems]
Setup_Halaacpi="Setup ACPI APIC UP (halaacpi.dll)"
Setup_Com+_Halaacpi="Setup (Debug+ COM) (halaacpi.dll)"
Setup_Screen_Halaacpi="Setup (Debug SCREEN) (halaacpi.dll)"
Setup_Screen+_Halaacpi="Setup (Debug+ SCREEN) (halaacpi.dll)"
Setup_LogFile+_Halaacpi="Setup (Debug+ Log file) (halaacpi.dll)"

LiveCD_Halaacpi="Live ACPI APIC UP (halaacpi.dll)"
LiveCD_Com+_Halaacpi="Live (Debug+ COM) (halaacpi.dll)"
LiveCD_Screen_Halaacpi="Live (Debug Screen) (halaacpi.dll)"
LiveCD_Screen+_Halaacpi="Live (Debug+ Screen) (halaacpi.dll)"
LiveCD_LogFile+_Halaacpi="Live (Debug+ Log file) (halaacpi.dll)"

LiveCD_RamDisk_Halaacpi="LiveCD ACPI APIC UP in RAM (halaacpi.dll)"
LiveCD_RamDisk_Com+_Halaacpi="LiveCD (Debug+ COM) in RAM (halaacpi.dll)"
LiveCD_RamDisk_Screen_Halaacpi="LiveCD (Debug Screen) in RAM (halaacpi.dll)"
LiveCD_RamDisk_Screen+_Halaacpi="LiveCD (Debug+ Screen) in RAM (halaacpi.dll)"
LiveCD_RamDisk_LogFile+_Halaacpi="LiveCD (Debug+ Log file) in RAM (halaacpi.dll)"

[Setup_Halaacpi]
BootType=ReactOSSetup
SystemPath=\bootcd
Options=/NOGUIBOOT /FIRSTCHANCE /HAL=halaacpi.dll

[Setup_Com+_Halaacpi]
BootType=ReactOSSetup
SystemPath=\bootcd
Options=/NOGUIBOOT /DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /ROS_DBG_FULL /FIRSTCHANCE /HAL=halaacpi.dll

[Setup_Screen_Halaacpi]
BootType=ReactOSSetup
SystemPath=\bootcd
Options=/DEBUG /DEBUGPORT=SCREEN:30,5,1 /SOS /HAL=halaacpi.dll

[Setup_Screen+_Halaacpi]
BootType=ReactOSSetup
SystemPath=\bootcd
Options=/DEBUG /DEBUGPORT=SCREEN:30,5,1 /ROS_DBG_FULL /SOS /HAL=halaacpi.dll

[Setup_LogFile+_Halaacpi]
BootType=ReactOSSetup
SystemPath=\bootcd
Options=/DEBUG /DEBUGPORT=FILE /ROS_DBG_FULL /SOS /HAL=halaacpi.dll

[LiveCD_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/MININT /MININT /HAL=halaacpi.dll

[LiveCD_Com+_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /ROS_DBG_FULL /SOS /MININT /HAL=halaacpi.dll

[LiveCD_Screen_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /SOS /MININT /HAL=halaacpi.dll

[LiveCD_Screen+_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /ROS_DBG_FULL /SOS /MININT /HAL=halaacpi.dll

[LiveCD_LogFile+_Halaacpi]
BootType=Windows2003
SystemPath=\livecd\reactos
Options=/DEBUG /DEBUGPORT=FILE /ROS_DBG_FULL /SOS /MININT /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\ArcName\multi(0)disk(0)rdisk(0)partition(1)\debug.log /SOS /MININT /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /MININT /HAL=halaacpi.dll

[LiveCD_RamDisk_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_Com+_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /ROS_DBG_FULL /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_Screen_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_Screen+_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /ROS_DBG_FULL /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll

[LiveCD_RamDisk_LogFile+_Halaacpi]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=FILE /ROS_DBG_FULL /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\ArcName\multi(0)disk(0)rdisk(0)partition(1)\debug.log /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /MININT /RDPATH=livecd\livecd.iso /RDEXPORTASCD /HAL=halaacpi.dll
