[FREELOADER]
DefaultOS=LiveCD_Com_Halaacpi
TimeOut=5

[Display]
TitleText=ReactOS LiveCD
StatusBarColor=Cyan
StatusBarTextColor=Black
BackdropTextColor=White
BackdropColor=Blue
BackdropFillStyle=Medium
TitleBoxTextColor=White
TitleBoxColor=Red
MessageBoxTextColor=White
MessageBoxColor=Blue
MenuTextColor=Default
MenuColor=Black
TextColor=Default
SelectedTextColor=Black
SelectedColor=Default
ShowTime=No
MenuBox=No
CenterMenu=No
MinimalUI=Yes
TimeText=Seconds until highlighted choice will be started automatically:   

[Operating Systems]
LiveCD_Halaacpi="Live ACPI APIC UP (halaacpi.dll)"
LiveCD_Com_Halaacpi="Live (Debug COM) (halaacpi.dll)"
LiveCD_Screen_Halaacpi="Live (Debug Screen) (halaacpi.dll)"
LiveCD_LogFile_Halaacpi="Live (Debug Log file) (halaacpi.dll)"

[LiveCD_Halaacpi]
BootType=Windows2003
SystemPath=\reactos
Options=/MININT /MININT /HAL=halaacpi.dll

[LiveCD_Com_Halaacpi]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /MININT /HAL=halaacpi.dll

[LiveCD_Screen_Halaacpi]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=SCREEN:30,4,1 /SOS /MININT /HAL=halaacpi.dll

[LiveCD_LogFile_Halaacpi]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=FILE /SOS /MININT /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\ArcName\multi(0)disk(0)rdisk(0)partition(1)\debug.log /SOS /MININT /HAL=halaacpi.dll
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /MININT /HAL=halaacpi.dll

