@ stdcall KdGetPacketAddress(ptr long)
@ stdcall KdGetPacketLength(ptr long)
@ stdcall KdGetRxPacket(ptr ptr ptr ptr)
@ stdcall KdGetTxPacket(ptr ptr)
@ stdcall KdInitializeController(ptr)
@ stdcall KdInitializeLibrary(ptr ptr ptr)
@ stdcall KdReleaseRxPacket(ptr long)
@ stdcall KdSendTxPacket(ptr long long)
@ stdcall KdSetHibernateRange()
@ stdcall KdShutdownController(ptr)
